
project:
  type: default
  render:
    - "_tutorials"

project:
  output-dir: .dev/build/.quarto

jupyter: .dev/python/venv/bin/python

format:
  html:
    toc: true
    code-copy: true
    css: /assets/code-animation/code-animation.css
    include-after-body:
      text: |
        <script src="/assets/code-animation/code-animation.js"></script>

execute:
  echo: true
  warning: false
  message: false
