
project:
  type: default
  render:
    - "_tutorials"

jupyter: .dev/python/venv/bin/python

format:
  html:
    theme: darkly
    toc: false
    code-copy: false
    css:
      - /assets/quarto/tutorial-style.css
      - /assets/code-animation/code-animation.css
    include-after-body:
      text: |
        <script src="/assets/code-animation/code-animation.js"></script>

execute:
  echo: true
  warning: false
  message: false
