name: ShepsBlog
title: The blog of J. Shepard Bryan IV.
description: The blog for J. Shepard Bryan IV.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: shepperoni.pizza@gmail.com
# See: https://disqus.com/
disqus_username: jsbryaniv
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: shepperoni.pizza@gmail.com
