
project:
  type: default
  render:
    - "**/*.qmd"

jupyter: python3

format:
  html:
    theme: darkly
    toc: false
    code-copy: false
    css:
      - .shared/tutorial-style/tutorial-style.css
      - .shared/code-animation/code-animation.css
    include-after-body:
      - .shared/code-animation/code-animation.html

execute:
  echo: true
  warning: false
  message: false
