---
title: "Python Tip: Understanding with"
subtitle: "Safer and simpler file handling"
author: "Shep Bryan IV"
description: "Learn how to use the with statement for safer and simpler file handling in Python."
---



<!-- PANEL 1 -->
:::{.tutorial-panel}

# Python Tip: Understanding `with`

`with` statements seem strange at first, but they are very simple!

`with` simplifies file handling while providing a robust safety net against human errors.

:::



<!-- PANEL 2 -->
:::{.tutorial-panel}

## Without `with`

You can open files without `with`, but you must remember to close the file.

:::{.code-animation}
```{python}

file = open('example.txt', 'w')  # 'w' for write
file.write("Hello, world!")
file.close()  # Don't forget to close the file!

file = open('example.txt', 'r')  # 'r' for read
content = file.read()
file.close()  # Don't forget to close the file!

print(content)  # Prints "Hello, world!"
```
:::

:::



<!-- PANEL 3 -->
:::{.tutorial-panel}

## With `with`

`with` statements not only simplify file handling, but also make it robust to human error.

:::{.code-animation}
```{python}
# 'w' for write
with open('example.txt', 'w') as file:
    file.write("Hello, world!")

# 'r' for read
with open('example.txt', 'r') as file:  
    content = file.read()

# Prints "Hello, world!"
print(content)
```
:::

:::



<!-- PANEL 4 -->
:::{.tutorial-panel}

## Why `with` is Important

Without `with`, small mistakes can cause unexpected behavior.

:::{.code-animation}
```{python}

file1 = open('example.txt', 'w')
file1.write("Hello, world!")
# Oops, I forgot to close the file...

file2 = open('example.txt', 'r')
content2 = file2.read()

# This returns an empty string
print(content2)
```
:::

Not closing files can also lead to resource issues or potential file access problems.

:::



<!-- PANEL 5 -->
:::{.tutorial-panel}

## With `with`, Code is Much Safer

The `with` statement automatically closes the file when the block ends, even if an error occurs.

:::{.code-animation}
```{python}

with open('example.txt', 'w') as file:
    file.write("Hello, world!")

with open('example.txt', 'r') as file:
    content = file.read()

print(content)  # Prints "Hello, world!"
```
:::

:::



<!-- PANEL 6 -->
:::{.tutorial-panel}

## Wrap-Up

Now you know how to make simple and robust file handling with `with`.

Follow me for more tips.  
Shep Bryan IV

:::
